import { Internships, Mentorship, Opportunities, Reviews } from "@/feature"
import { Container } from "@mantine/core"
import Head from "next/head"

import { Navbar } from "@/widgets"

const HomePage = () => {
	return (
		<>
			<Head>
				<title>Freshman Careers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Internships />
			<Opportunities />
			<Container size={"1440px"}>
				<Mentorship />
			</Container>
			<Reviews />
		</>
	)
}

export default HomePage
