import {
	Faq,
	Internships,
	Mentorship,
	Opportunities,
	Reviews,
	Webinar,
} from "@/feature"
import Head from "next/head"

import { Navbar, Footer } from "@/widgets"

const HomePage = () => {
	return (
		<>
			<Head>
				<title>Freshman Careers</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Internships />
			<Opportunities />
			<Mentorship />
			<Reviews />
			<Webinar />
			<Faq />
			<Footer/>
		</>
	)
}

export default HomePage
