import { InternshipProfile } from "@/feature"
import Head from "next/head"
import React from "react"

import { NavbarProfile } from "@/widgets"
import dynamic from "next/dynamic"
const PrivateRoute = dynamic(() => import('@/widgets/private-route'), { ssr: false })

const ProfilePage = () => {
	return (
		<>
			<PrivateRoute>
				<Head>
					<title>My Applicationss</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<NavbarProfile />
				<InternshipProfile />
			</PrivateRoute>
		</>
	)
}

export default ProfilePage
