import Head from "next/head"
import React from "react"
import { NavbarProfile } from "@/widgets"
import { InternshipProfile } from "@/feature"

const ProfilePage = () => {
	return (
		<>
			<Head>
				<title>My Applicationss</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavbarProfile/>
			<InternshipProfile/>
		</>
	)
}

export default ProfilePage
