import { MyProfile } from "@/feature"
import dynamic from "next/dynamic"
import Head from "next/head"
import React from "react"

import { NavbarProfile } from "@/widgets"

const PrivateRoute = dynamic(() => import("@/widgets/private-route"), {
	ssr: false,
})

const ProfilePage = () => {
	return (
		<>
			<PrivateRoute>
				<Head>
					<title>My Profile</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<NavbarProfile />
				<MyProfile />
			</PrivateRoute>
		</>
	)
}

export default ProfilePage
