export enum apiKeys {
	signIn = "auth/signin",
	signUp = "/auth/signup/step1",
	newPassword = "/auth/signup/step2",
	internships = "internships",
	mentorships = "/mentorships",
	myApplications = "account/internships",
	userMe = "account/me",
	userImage = "account/image",
	userFiles = "account/files",
	changePassword = "account/password",
	subscription = "/account/subscribe",
	unSubscription = "/account/unsubscribe",
	accountSuccess = "/account/check-status",
	subscriptionRenewal = "/account/subscription/renewal",
}
