export enum apiKeys {
	signIn = "auth/signin",
	signUp = "/auth/signup/step1",
	newPassword = "/auth/signup/step2",
	internships = "admin/internships",
	myApplications = "account/internships",
	userMe = "account/me",
	accountApply = "account/apply",
	userFiles = "account/files",
	changePassword = "account/password",
	subscription = "/account/subscribe",
	unSubscription = "/account/unsubscribe",
	accountSuccess = "/account/check-status",
	subscriptionRenewal = "/account/subscription/renewal",
	responses = "/account/applications",
	applicationsSubmit = "/applications/submit",
	resetPassword = "/auth/reset-password-request",
	confirmResetCode = "/auth/confirm-reset-code",
	confirmPasswordReset = "/auth/confirm-password-reset",
}
